---
- hosts: jenkins

  pre_tasks:
    # Work around https://github.com/geerlingguy/ansible-role-jenkins/issues/47
    - name: Fetch Jenkins 1.651
      get_url:
        url: http://mirrors.jenkins-ci.org/redhat-stable/jenkins-1.651.1-1.1.noarch.rpm
        dest: /tmp/jenkins-1.651.1-1.1.noarch.rpm
    - name: Install Jenkins 1.651
      yum: name=/tmp/jenkins-1.651.1-1.1.noarch.rpm

  gather_facts: yes

  vars_files:
      - vars/main.yml

  roles:
      - geerlingguy.firewall
      - geerlingguy.ntp
      - geerlingguy.git
      - geerlingguy.java
      - geerlingguy.jenkins
      - geerlingguy.nodejs
      - ansible-role-jenkins-job-builder
      - custom_jenkins_plugins
